### ISSUE TITLE
Modelview not loading 

### ISSUE THREAD

**Issue by PicassoCT** [mortennobel/KickJS#73]
Hi, i worked on a shader with your great side.
I can see everything i do, but it turns out, once i share my work or come back to it, it wont load the textures.
The shader compiles correctly.

http://goo.gl/Llbvkv

Regards

**Comment by mortennobel** [comment]
I'll take a look at the problem :)

Kind Regards,
Morten

**Comment by PicassoCT** [comment]
Hi, 
i tried to reproduce it.
Seems the loading of a saved shader works fine.
Its actually only if you venture in via a share link.
Once the link version is used, the texture binding seems broken -
 even if you try to load the saved version.

Would patch it, if i had the time to read in 
You framework is great, especially the texture loading. 

Regards

**Comment by mortennobel** [comment]
Fixed
